package com.example.thesisrepo.notification;

public enum NotificationEvent {

  ACCOUNT_CREATED,

  REGISTRATION_SUBMITTED,
  SUPERVISOR_APPROVED_REGISTRATION,
  LIBRARY_APPROVED_REGISTRATION,

  SUBMISSION_UPLOADED,
  SUPERVISOR_FEEDBACK,
  SUPERVISOR_APPROVED_SUBMISSION,

  LIBRARY_FEEDBACK,
  LIBRARY_APPROVED_SUBMISSION,

  CLEARANCE_APPROVED,

  LECTURER_SELECTED_SUPERVISOR,
  LECTURER_NEW_SUBMISSION,
  LECTURER_LIBRARY_APPROVAL,

  ADMIN_NEW_REGISTRATION,
  ADMIN_SUPERVISOR_FORWARD,
  ADMIN_RESUBMISSION,
  ADMIN_CLEARANCE_SIGNED
}
