package com.example.thesisrepo.publication;

public enum AuditEventType {
  REGISTRATION_DRAFT_SAVED,
  REGISTRATION_SUBMITTED,
  SUBMISSION_UPLOADED,
  CLEARANCE_SUBMITTED,
  SUPERVISOR_APPROVED_REGISTRATION,
  SUPERVISOR_REJECTED_REGISTRATION,
  SUPERVISOR_REQUESTED_REVISION,
  SUPERVISOR_MARKED_READY,
  SUPERVISOR_FORWARDED_TO_LIBRARY,
  LIBRARY_APPROVED_REGISTRATION,
  LIBRARY_REJECTED_REGISTRATION,
  LIBRARY_CHECKLIST_REVIEWED,
  LIBRARY_REQUESTED_REVISION,
  LIBRARY_APPROVED_FOR_CLEARANCE,
  LIBRARY_REJECTED,
  CLEARANCE_APPROVED,
  CLEARANCE_CORRECTION_REQUESTED,
  UNPUBLISHED_FOR_CORRECTION,
  PUBLISHED,
  FEEDBACK_ADDED
}
