package com.example.thesisrepo.publication;

public enum CaseStatus {
  REGISTRATION_DRAFT,
  REGISTRATION_PENDING,
  REGISTRATION_APPROVED,
  REGISTRATION_VERIFIED,
  UNDER_SUPERVISOR_REVIEW,
  NEEDS_REVISION_SUPERVISOR,
  READY_TO_FORWARD,
  FORWARDED_TO_LIBRARY,
  UNDER_LIBRARY_REVIEW,
  NEEDS_REVISION_LIBRARY,
  APPROVED_FOR_CLEARANCE,
  CLEARANCE_SUBMITTED,
  CLEARANCE_APPROVED,
  READY_TO_PUBLISH,
  PUBLISHED,
  REJECTED
}
