DROP TABLE IF EXISTS thesis_checklist CASCADE;
DROP TABLE IF EXISTS checklist_item CASCADE;
DROP TABLE IF EXISTS supervisor_assignment CASCADE;
DROP TABLE IF EXISTS approval CASCADE;
DROP TABLE IF EXISTS thesis CASCADE;
